version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    #    entrypoint: [ "./entrypoint.sh" ]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dionysas-db:/var/lib/mysql
# Names our volume
volumes:
  dionysas-db:
